[package]
name = "client"
version = "0.1.0"
edition = "2021"
authors = ["Shuocheng Wang <wangshch5@outlook.com>"]

[dependencies]
tokio = { version = "1", features = ["full"] }
tokio-rustls = "0.26.0"
simple-cypher = { path = "../crates/simple-cypher" }