[package]
name = "simple-cypher"
version = "0.1.0"
edition = "2021"
authors = ["Shuocheng Wang <wangshch5@outlook.com>"]

[dependencies]
anyhow = "1.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"